#!/bin/bash

export HOME=`pwd`

git branch -D master
git checkout -b master

time repo init -u . -b master
time repo sync -j20

TEMPLATECONF=`pwd`/sources/meta-qtipi/misc source sources/poky/oe-init-build-env build
bitbake core-image-qtipi
